name = 'seb-doc'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/matharel/seb-doc'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'SÃ©bastien Matharel', homepage = ''},
]
